@extends('layout.main')
@section('page-container')
<?php
use Illuminate\Support\Str;
use App\Models\language;
$lang = language::language();
?>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="stylepp.css">
    <title>Krishi Vikas Udyog</title>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap');

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            //font-family: 'Oswald', sans-serif;
        }

        .terms-of-use {
            width: 100%;
            padding: 50px;
            text-align: center;
            display: grid;
            align-content: center;
        }

        .terms-of-use p {

            text-align: justify;
            margin: 0 auto;
        }

        .terms-of-use ul {
            display: grid;
            align-content: center;
            text-align: justify;
            list-style-type: none;
            margin: 0 auto;
        }
    </style>


<body>

    <div class="terms-of-use">
        <h1>Welcome to Krishi Vikas’s Terms of Use</h1>
        <p>This legal agreement is an electronic record in terms of the Information Technology Act, 2000 and rules there
            under as applicable and the amended provisions about electronic records in various statutes as amended by
            the Information Technology Act, 2000. This electronic record is generated by a computer system and does not
            require any physical or digital signatures.
            This legal document is published in accordance with the provisions of Rule 3 (1) of the Information
            Technology (Intermediaries guidelines) Rules, 2011 and Rule 4 of the Information Technology (Reasonable
            security practices and procedures and sensitive personal data or information) Rules, 2011 of Information
            Technology Act, 2000 amended through Information Technology Amendment Act, 2008 that require publishing the
            Terms of Use and practices for access and usage of any functional Application.

            This Application is created and operated by M/s Abybaby E-Com Private Limited, is a private limited company
            duly incorporated under the provisions of Companies Act, 2013 (hereinafter referred to as “We”, “Our”, and
            “Us”) having its registered address at Ground Floor, 4B, Rani Bhabani Road, Kolkata, West Bengal - 700026
            and operating under the brand name “Krishi Vikas” (“Brand Name”). We intend to ensure your steady commitment
            to the usage of this Application and the services provided by us through our Application “Krishi Vikas”
            (“Application”).

        <ul>
            <li>i. For the purpose of these Terms of Use (“Terms of Use”), wherever the context so requires, “We”,
                “Firm”, “Our”, and “Us” shall mean and refer to the Application. </li>
            <li>ii. “You”, “Your”, “Yourself”, “User”, “Vendor”, “Service Provider” and “Customer” shall mean and refer
                to natural and legal individuals who shall be users of this Application provided by us and who is
                competent to enter into binding contracts, as per Indian laws. </li>
            <li>iii. “Third Parties” refer to any Application or individual apart from the Users and the creator of this
                Application.</li>
        </ul>
        </p>

        <h1>GENERAL TERMS</h1>
        <ul>
            <li>i. The headings of each section in these Terms of Use are only for the purpose of organizing the various
                provisions under these Terms of Use in an orderly manner and shall be used by you to interpret the
                provisions contained herein in a manner as may apply to you. Further, it is specifically agreed by you
                that the headings shall have legal or contractual value on your usage of the Application.</li>

            <li>ii. The use of this Application is solely governed by these Terms of Use, Privacy Policy that may be
                uploaded on the Application and any modifications or amendments made thereto by us from time to time, at
                our sole discretion. If you as a user continue to access and use this Application, you are agreeing to
                comply with and be bound by the following Terms of Use and Privacy Policy.</li>
            <li>iii. You expressly agree and acknowledge that these Terms of Use and Privacy Policy are co-terminus in
                nature and that expiry/termination of either one will lead to the termination of the other.</li>
            <li>iv. You unequivocally agree that these Terms of Use and the Privacy Policy constitute a legally binding
                agreement between us, and that you shall be subject to the rules, guidelines, policies, terms, and
                conditions applicable to your use of the Application, and that the same shall be deemed to be
                incorporated into these Terms of Use and shall be treated as part and parcel of the same. You
                acknowledge and agree that no signature or express act is required to make these Terms of Use and the
                Privacy Policy binding on you and that your act of visiting any part of the Application constitutes your
                full and final acceptance of these Terms of Use and the Privacy Policy.</li>
            <li>v. We reserve the sole and exclusive right to amend or modify these Terms of Use without any prior
                permission or intimation to you, and you expressly agree that any such amendments or modifications shall
                come into effect immediately. If you do not adhere to the changes, You must stop using the Application
                at once. Your continued use of the Application will signify your acceptance of the changed terms.</li>
        </ul>


        <h1>REGISTRATION </h1>
        <p>Registration on the Application is mandatory for Users of the Applications. The Users shall have to provide
            the following information at the time of registration.</p>
        <ul>
            <li>i. Name</li>
            <li>ii. Phone Number</li>
            <li>iii. Email ID</li>
            <li>iv. Geo-location</li>
            <li>v. Date of Birth</li>
            <li>vi. Photo </li>

        </ul>

        <p>The Users can also link their social media accounts such as Google and Facebook at the time of signing up on
            the Application.</p>

        <h1>PAYMENT GATEWAY</h1>
        <p>For making all payments for services on the Application, you shall be required to make payment for which you
            will be redirected to a third-party payment gateway, that we may have an agreement with. The payment gateway
            may additionally seek information from you to process the payment for your purchase and additionally may
            charge you the payment gateway charges that may be applicable. The payment gateway consists of Razor pay/
            Debit Card/Credit Card/Net Banking/UPI and other wallet options. You shall be governed under the concerned
            payment gateway’s Terms and Conditions and other Policies for the purpose of all payment-related aspects.
        </p>

        <h1>ELIGIBILITY</h1>
        <ul>
            <li>a) You represent and warrant that you are competent and eligible to enter into legally binding
                agreements and of age and that you have the requisite authority to bind themselves to these Terms of Use
                following the Law. However, if you are a minor using this Application, you may do so with the consent of
                your legal guardian. All Acts of minor shall be deemed to be considered as the acts undertaken under the
                supervision of their legal guardian.</li>
            <li>b) You further represent that you will comply with these Terms of Use and all applicable local, state,
                national and international laws, rules and regulations.</li>
            <li>c) You shall not use the Application if you are not competent to contract or are disqualified from doing
                so by any other applicable law, rule or regulation currently in force.</li>
        </ul>

        <h1>CONTENT</h1>
        <p>All text, advertisement, graphics, User interfaces, visual interfaces, photographs, trademarks, logos, brand
            names, descriptions, sounds, music and artwork (collectively, ‘Content’), is generated/provided or based on
            information provided by the users or third parties and We have no control and make no guarantees regarding
            the quality, the accuracy, integrity or genuineness of such content or such other information provided on
            the Application. <br>
            All the Content displayed on the Application is subject to copyright and shall not be reused by You (or a
            third party) without the prior written consent from Us and the copyright owner. <br>
            You are solely responsible for the integrity, authenticity, quality and genuineness of the content provided
            on the Application and whilst feedback and comments by You can be made via the Application, we bear no
            liability whatsoever for any feedback or comments made by the other Users or made in respect of any of the
            content on the Application. Further, the Application reserves its right to suspend the account of any User
            for an indefinite period to be decided at the discretion of the Application or to terminate the account of
            any User who is found to have created or shared or submitted any content or part thereof that is found to be
            untrue/inaccurate/misleading or offensive/vulgar. You shall be solely responsible for making good any
            financial or legal losses incurred through the creation/sharing/submission of Content or part thereof that
            is deemed to be untrue/inaccurate/misleading. <br>
            You have a personal, non-exclusive, non-transferable, revocable, limited privilege to access the content on
            the Application. You shall not copy, adapt, and modify any content without written permission from Us.
        </p>

        <h1>INDEMNITY</h1>
        <p>You agree to indemnify, defend and hold harmless the Us, and our respective directors, officers, employees
            and agents (collectively, "Parties"), from and against any losses, liabilities, claims, damages, demands,
            costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable
            thereon) asserted against or incurred by Us that arise out of, result from, or maybe payable by, any breach
            or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed
            according to these Terms of Use. Further, You agrees to hold the Us harmless against any claims made by any
            third party due to, or arising out of, or in connection with:
        <ul>
            <li>a. Your use of the Application, </li>
            <li>b. Your violation of these Terms of Use; </li>
            <li>c. Your violation of any rights of another; </li>
            <li>d. Your alleged improper conduct according to these Terms of use;</li>
            <li>e. Your conduct in connection with the Application; </li>
        </ul>
        </p>
        <p>You agree to fully cooperate in indemnifying Us at your expense. You also agree not to settle with any party
            without consent from Us. <br>
            In no event shall we be liable to compensate You or any third party for any special, incidental, indirect,
            consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits,
            whether or not foreseeable, and whether or not You had been advised of the possibility of such damages, or
            based on any theory of liability, including breach of contract or warranty, negligence or other tortuous
            action, or any other claim arising out of or in connection with the Your use of or access to the Application
            and/or the Services or materials contained therein.
        </p>

        <h1>LIMITATION OF LIABILITY</h1>
        <ul>
            <li>a. We are not responsible for any consequences arising out of the following events:
                <br>
                i. If the Application is inoperative/non-responsive due to any connectivity errors associated with the
                internet connection such as but not limited to slow connectivity, no connectivity, server failure;
                ii. If you have fed incorrect information or data or for any deletion of data;
                iii. If there is an undue delay or inability to communicate through email;
                iv. If there is any deficiency or defect in the Services managed by Us;
                v. If there is a failure in the functioning of any other service provided by Us.
            </li>

            <li>b. The Application accepts no liability for any errors or omissions, on behalf of itself, or for any
                damage caused to You, Your belongings, or any third party, resulting from the use or misuse of the
                Application or any service availed of by Us through the Application. The service and any Content or
                material displayed on the service is provided without any guarantees, conditions or warranties as to its
                accuracy, suitability, completeness or reliability. We will not be liable to you for the unavailability
                or failure of the Application.</li>

            <li>c. You are to comply with all laws applicable to you or your activities, and with all Policies, which
                are hereby incorporated into this Terms of Use by reference.</li>
            <li>d. The Application expressly excludes any liability for any loss or damage that was not reasonably
                foreseeable by the Application and which is incurred by you in connection with the Application,
                including loss of profits; and any loss or damage incurred by you as a result of your breach of these
                Terms of Use.</li>

            <li>e. To the fullest extent permitted by law, We shall not be liable to You or any other party for any loss
                or damage, regardless of the form of action or basis of any claim. You acknowledge and agree that your
                sole and exclusive remedy for any dispute with us is to terminate your use of the Application.</li>
        </ul>



        <h1>TERM</h1>
        <ul>
            <li>a. These Terms of Use shall continue to form a valid and binding contract between us and shall continue
                to be in full force and effect until you continue to access and use the Applications.</li>
            <li>b. You may terminate your use of the Application at any time. </li>
            <li>c. We may terminate these Terms of Use and close your account at any time without notice and/or suspend
                or terminate Your access to the Application at any time and for any reason, if any discrepancy or legal
                issue arises.</li>
            <li>d. Such suspension or termination shall not limit our right to take any other action against you that we
                consider appropriate.</li>
            <li>e. It is also hereby declared that we may discontinue the Services and Applications without any prior
                notice.</li>
        </ul>


        <h1>TERMINATION</h1>
        <ul>
            <li>a. We reserve the right, in its sole discretion, to unilaterally terminate Your access to the
                Application, or any portion thereof, at any time, without notice or cause. </li>
            <li>b. We also reserve the universal right to deny access to You, to any/all of are on its Application
                without any prior notice/explanation to protect the interests of the Application and/or other Users to
                the Application. </li>
            <li>c. We reserve the right to limit, deny or create different access to the Application and its features
                concerning different Users, or to change any of the features or introduce new features without prior
                notice. </li>

            <li>d. You shall continue to be bound by these Terms of use, and it is expressly agreed to by You that You
                shall not have the right to terminate these Terms of Use till the expiry of the same.</li>


        </ul>




        <h1>COMMUNICATION</h1>
        <p>By using this Application and providing Your identity and contact information to Us through the Application,
            You agree and consent to receive calls, e-mails or SMS from Us and/or any of its representatives at any
            time.
            You can report to support@krishivikas.com if you find any discrepancy with regard to Application or
            content-related information and we will take necessary action after an investigation. The response with
            resolution (if any issues found) shall be dependent on the time is taken for investigation.
            You expressly agree that notwithstanding anything contained herein above, it may be contacted by Us relating
            to any services availed by You on the Application or anything pursuant thereto and You agree to indemnify Us
            from any harassment claims. It is expressly agreed to by Us that any information shared by Us shall be
            governed by the Privacy Policy.
        </p>

        <h1>USER OBLIGATIONS AND FORMAL UNDERTAKINGS AS TO CONDUCT</h1>
        <p>You agree and acknowledges that you are a restricted user of this Application and you:
        <ul>
            <li>a.Agree to provide genuine credentials during the process whenever required on the Application. You
                shall not use a fictitious identity to register. We are not liable if you have provided incorrect
                information. </li>
            <li>b.Agree to ensure the Name, Email address, Address, Mobile number and any such other information that
                may be provided during account registration is valid at all times and shall keep your information
                accurate and up-to-date.</li>
            <li>c.You agree that You are solely responsible for maintaining the confidentiality of your account
                password. You agree to notify us immediately of any unauthorized use of your account. We reserve the
                right to close your account at any time for any or no reason.</li>

            <li>d. User represents and warrants that the Firm may offer other additional accidental insurance packages
                from any third parties, which will benefit the user. However, the Firm does not guarantee the user the
                same at any time.</li>

            <li>e. Authorize the Application to use, store or otherwise process certain personal information and all
                published Content, responses, locations, User comments, reviews and ratings for personalization of
                Services, marketing and promotional purposes and for optimisation of User-related options and Services.
            </li>

            <li>
                f.Understand and agree that, to the fullest extent permissible by law, the Application or any of their
                affiliates or their respective officers, directors, employees, agents, licensors, representatives,
                operational service providers, advertisers or suppliers shall not be liable for any loss or damage, of
                any kind, direct or indirect, in connection with or arising from the use of the Application or this
                terms of use, including, but not limited to, compensatory, consequential, incidental, indirect, special
                or punitive damages.
            </li>

            <li>g. Are bound not to cut, copy, modify, recreate, reverse engineer, distribute, disseminate, post,
                publish or create derivative works from, transfer, or sell any information or obtained from the
                Application. Any such use/limited use of the Application will only be allowed with the prior express
                written permission. </li>

            <li>h.Agree that promotions and giveaways are governed by a different set of rules. </li>

            <li>i.Agree not to access (or attempt to access) the Application and/or the materials or Services by any
                means other than through the interface provided by the Application. The use of deep-link, robot, spider
                or other automatic devices, program, algorithm or methodology, or any similar or equivalent manual
                process, to access, acquire, copy or monitor any portion of the Application or its content, or in any
                way reproduce or circumvent the navigational structure or presentation of the Application, materials or
                any content, or to obtain or attempt to obtain any materials, documents or information through any means
                not specifically made available through the Application will lead to suspension or termination of your
                access to the Application. We disclaim any liabilities arising concerning such offensive content on the
                Application. </li>

            <li>j.Expressly agree and acknowledge that the Content generated by the Users and displayed on the
                Application is not owned by Us and that We are in no way responsible for the content of the same. You
                may, however, report any offensive or objectionable content, which We may then remove from the
                Application, at our sole discretion.</li>

            <li>You further undertake not to:
                <ul>
                    <li>a.Engage in any activity that interferes with or disrupts access to the Application or the
                        services provided therein (or the servers and networks which are connected to the Application);
                    </li>
                    <li>b.Impersonate any person or entity, or falsely state or otherwise misrepresent his/her
                        affiliation with a person or entity;</li>

                    <li>c.Probe, scan or test the vulnerability of the Application or any network connected to the
                        Application, nor breach the security or authentication measures on the Application or any
                        network connected to the Application. The User may not reverse look-up, trace or seek to trace
                        any information relating to any other User of, or visitor to, the Application, or any other
                        viewer of the Application, including any User account maintained on the Application not
                        operated/managed by the User, or exploit the Application or information made available or
                        offered by or through the Application, in any manner;</li>
                    <li>d.Disrupt or interfere with the security of, or otherwise cause harm to, the Application,
                        systems resources, accounts, passwords, servers, or networks connected to or accessible through
                        the Application or any affiliated or linked Applications.</li>
                    <li>e.Use the Application or any material or content therein for any purpose that is unlawful or
                        prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other
                        activity which infringes the rights of this Application or any other third party (s);</li>
                    <li>f.Violate any code of conduct or guideline which may apply for or to any particular service
                        offered on the Application;</li>
                    <li>g.Violate any applicable laws, rules or regulations currently in force within or outside India;
                    </li>
                    <li>h.Violate any portion of these Terms of Use or the Privacy Policy, including but not limited to
                        any applicable additional terms of the Application contained herein or elsewhere, whether made
                        by amendment, modification, or otherwise;</li>
                    <li>i.Commit any act that causes Us to lose (in whole or in part) the Services of its Internet
                        Establishment ("ISP") or in any manner disrupts the Services of any other supplier/service
                        provider of the Application;</li>
                    <li>j.You hereby expressly authorize Us to disclose any and all information relating to You in our
                        possession to law enforcement or other government officials, as We may in our sole discretion,
                        believe necessary or appropriate in connection with the investigation and/or resolution of
                        possible crimes, especially those involve personal injury and theft/infringement of intellectual
                        property. You further understand that the Application might be directed to disclose any
                        information (including the identity of persons providing information or materials on the
                        Application) as necessary to satisfy any judicial Order, law, regulation or valid governmental
                        request.</li>
                    <li>k.By indicating Your acceptance to use any services offered on the Application, You are
                        obligated to complete such transactions after making payment. You shall be prohibited from
                        indicating their acceptance to avail services where the transactions have remained incomplete.
                    </li>
                    <li>l.You agree to use the services provided by Us, our affiliates, consultants and contracted
                        companies, for lawful purposes only.</li>
                    <li>m.You agree to provide authentic and true information. We reserve the right to confirm and
                        validate the information and other details provided by You at any point in time. If upon
                        confirmation such details are found to be false, not to be true (wholly or partly), We shall in
                        our sole discretion reject the registration and debar You from using the Application without
                        prior intimation whatsoever.</li>
                    <li>n.You agree not to post any material on the Application that is defamatory, offensive, obscene,
                        indecent, abusive, or needlessly distressful or advertising any goods or services. More
                        specifically, You agree not to host, display, upload, update, publish, modify, transmit, or in
                        any manner share any information that:
                        <ul>
                            <li>i. belongs to another person and to which you have no right to;</li>
                            <li>ii. is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic,
                                pedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically
                                objectionable, disparaging, relating or encouraging money laundering or gambling, or
                                otherwise unlawful in any manner whatever;</li>
                            <li>iii. is in any way harmful to minors;</li>
                            <li>iv. infringes any patent, trademark, copyright or other proprietary rights;</li>
                            <li>v. violates any law for the time being in force;</li>
                            <li>vi. deceives or misleads the addressee about the origin of such messages or communicates
                                any information which is grossly offensive or menacing;</li>
                            <li>vii. Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise
                                violate the legal rights of others;</li>
                            <li>viii. Impersonate any person or entity, or falsely state or otherwise misrepresent Your
                                affiliation with a person or entity;</li>
                            <li>ix. Publish, post, disseminate, any grossly harmful information, harassing, blasphemous,
                                defamatory, obscene, pornographic, pedophilic, libellous, invasive of another's privacy,
                                hateful, or racially, ethnically objectionable, disparaging, relating or encouraging
                                money laundering or gambling, or otherwise unlawful in any manner whatever; or
                                unlawfully threatening or unlawfully harassing including but not limited to "indecent
                                representation of women" within the meaning of the Indecent Representation of Women
                                (Prohibition) Act, 1986;</li>
                            <li>x. Threatens the unity, integrity, defence, security or sovereignty of India, friendly
                                relations with foreign states, or public order or causes incitement to the commission of
                                any cognizable offence or prevents investigation of any offence or is insulting any
                                other nation.</li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
        </p>

        <h1>SUSPENSION OF USER ACCESS AND ACTIVITY</h1>
        <p>Notwithstanding other legal remedies that may be available, we may in our sole discretion, limit your access
            and/or activity by immediately removing your access credentials either temporarily or indefinitely, or
            suspend/terminate your association with the Application, and/or refuse to the usage of the Application,
            without being required to provide you with notice or cause:</p>
        <ul>
            <li>a. If you are in breach of any of these Terms of Use or the Privacy Policy;</li>
            <li>b. If you have provided wrong, inaccurate, incomplete or incorrect information;</li>
            <li>c. If your actions may cause any harm, damage or loss to the other Users or Us, at our sole discretion.
            </li>
        </ul>

        <h1>INTELLECTUAL PROPERTY RIGHTS</h1>
        <p>Unless expressly agreed to in writing, nothing contained herein shall give you a right to use any of the
            trade names, trademarks, service marks, logos, domain names, information, questions, answers, solutions,
            reports and other distinctive brand features, save according to the provisions of these Terms of Use that
            shall be available on the Application. All logos, trademarks, brand names, service marks, domain names,
            including material, designs, and graphics created by and developed by either the Application or such other
            third party and other distinctive brand features of the Application are the property of the Application or
            the respective copyright or trademark owner. Furthermore, concerning the Application, we shall be the
            exclusive owner of all the designs, graphics and the like, related to the Application. <br>
            You shall not use any of the intellectual property displayed on the Application in any manner that is likely
            to cause confusion among existing or prospective users of the Application, or that in any manner disparages
            or discredits the Application, to be determined in the sole discretion. <br>
            You are aware all intellectual property, including but not limited to copyrights, relating to said services
            resides with the owners, and that at no point does any such intellectual property stand transferred from the
            aforementioned creators. You are aware that we merely provide the Application through which You can
            communicate with other users and the Application does not own any of the intellectual property relating to
            the independent content displayed on the Application, apart from created graphics and specified content.
            <br>
            You are further aware that any reproduction or infringement of the intellectual property of the
            aforementioned owners by You will result in legal action being initiated against You by the respective
            owners of the intellectual property so reproduced/infringed upon. It is agreed to by You that the contents
            of this section shall survive even after the termination or expiry of these Terms of Use and/or Privacy
            Policy.
        </p>

        <h1>DISCLAIMER OF WARRANTIES AND LIABILITIES</h1>
        <ul>
            <li>a.You further agree and undertake that you are accessing the Application at your sole risk and are that
                you are using the best and prudent judgment before availing of any features on the Application or
                accessing/using any information displayed thereon.</li>
            <li>b.You agree that any kind of information, resources, activities, recommendations obtained/availed from
                the Application, written or oral, will not create any warranty and we disclaim all liabilities resulting
                from these. </li>
            <li>c.We do not guarantee that the features and content contained in the Application will be uninterrupted
                or error-free, or that the Application or its server will be free of viruses or other harmful
                components, and You hereby expressly accepts any associated risks involved with your use of the
                Application.</li>
            <li>d.It is further agreed to by You that the contents of this section shall survive even after the
                termination or expiry of the Terms of Use and/or Privacy Policy.</li>
        </ul>

        <h1>FORCE MAJEURE</h1>
        <p>We will not be liable for damages for any delay or failure to perform our obligations hereunder if such delay
            or failure is due to cause beyond our control or without its fault or negligence, due to Force Majeure
            events including but not limited to acts of war, acts of God, earthquake, riot, fire, festive activities
            sabotage, labour shortage or dispute, internet interruption, technical failure, breakage of sea cable,
            hacking, piracy, cheating, illegal or unauthorized.</p>

        <h1>DISPUTE RESOLUTION AND JURISDICTION</h1>
        <p>In the event of any dispute arising out of or in connection with this agreement, including any dispute
            relating to the validity of this agreement, the parties shall, at first instance, attempt to resolve the
            dispute by mediation administered by the Centre for Online Resolution of Disputes (“CORD”)
            (www.resolveoncord.com) and conducted in accordance with the CORD Rules of Mediation, by a sole mediator to
            be appointed by CORD.
            In the event the parties are unable to resolve any such dispute through mediation within 45 days of the
            initiation of the dispute, subject to a contrary agreement between the parties, the dispute shall be finally
            resolved by arbitration administered by CORD and conducted in accordance with the Rules of Arbitration of
            CORD, by a sole arbitrator to be appointed by CORD. The language of arbitration shall be English. The seat
            of arbitration shall be Kolkata, India.
            You expressly agree that the Terms of Use, Privacy Policy and any other agreements entered into between the
            Parties are governed by the laws, rules, and regulations of India.
        </p>

        <h1>MISCELLANEOUS PROVISIONS</h1>
        <ul>
            <li><strong>a. Entire Agreement:</strong> These Terms of Use, read with the Privacy Policy, form the
                complete and final contract between us with respect to the subject matter hereof and supersedes all
                other communications, representations, and agreements (whether oral, written or otherwise) relating
                thereto.</li>
            <li> <strong>b. Waiver: </strong> The failure at any time to require performance of any provision of these
                Terms of Use shall
                in no manner affect our right at a later time to enforce the same. No waiver by us of any breach of
                these Terms of Use, whether by conduct or otherwise, in any one or more instances, shall be deemed to be
                or construed as a further or continuing waiver of any such breach, or a waiver of any other breach of
                these Terms of Use. </li>
            <li><strong>c. Severability:</strong> If any provision/clause of these Terms of Use is held to be invalid,
                illegal or
                unenforceable by any court or authority of competent jurisdiction, the validity, legality, and
                enforceability of the remaining provisions/clauses of these Terms of Use shall in no way be affected or
                impaired thereby, and each such provision/clause of these Terms of Use shall be valid and enforceable to
                the fullest extent permitted by law. In such case, these Terms of Use shall be reformed to the minimum
                extent necessary to correct any invalidity, illegality or unenforceability, while preserving to the
                maximum extent the original rights, intentions and commercial expectations of the Parties hereto, as
                expressed herein. </li>
            <li><strong>d. Contact Us:</strong> If you have any questions about these Terms of Use, the practices of the
                Application, or
                your experience, you can contact us by emailing at support@krishivikas.com or by writing to us at :
            </li>

            <p>
                M/s Abybaby E-Com Private Limited,
                Ground Floor, 4B, Rani Bhabani Road,
                Kolkata, West Bengal - 700026

            </p>
        </ul>
    </div>

</body>

@endsection